In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np


In [2]:
iris = load_iris()

In [3]:
pd.DataFrame(data = iris.data,columns =iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
x = iris.data
y = iris.target

In [5]:
x.shape

(150, 4)

In [6]:
y.shape

(150,)

Hold out


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
x_train.shape

(105, 4)

In [ ]:
x_test.shape

(45, 4)

In [ ]:
y_train.shape

(105,)

In [ ]:
y_test.shape

(45,)

k fold

In [ ]:
from sklearn.model_selection import KFold


In [ ]:
x = [0,1,2,3,4,5,6,7,8]

In [ ]:
kf = KFold(n_splits=2)

In [ ]:
kf

KFold(n_splits=2, random_state=None, shuffle=False)

In [ ]:
for train,test in kf.split(x):
  print(train,test)

[5 6 7 8] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8]


In [ ]:
kf2 = KFold(n_splits=5)

In [ ]:
for train,test in kf2.split(x):
  print(train,test)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [ ]:
kf3 = KFold(n_splits=9)
for train,test in kf3.split(x):
  print(train,test)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


k nearest neighbour classification using holdout method:

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
prediction_knn = knn.predict(x_test)

classification metrics

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
print("Accuracy on the test data")
print(accuracy_score(y_test,prediction_knn))

print("classification report on the test data")
print(classification_report(y_test,prediction_knn))

Accuracy on the test data
0.9777777777777777
classification report on the test data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.95      1.00      0.97        18
           2       1.00      0.92      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45

